version: '3.9'

networks:
  api_network:

volumes:
  chrisshop_sql_data:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123
    ports:
      - "3306:3306"
    volumes:
      - chrisshop_sql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api_network
